# Required to run your project under the correct environment.

language: php

# Versions of PHP you want your project run with.

php:

 - 5.5


# After a build, send email notification with the build results
notifications:
 email: raj@immanuel.co
